import Head from "next/head";
import Container from "react-bootstrap/Container";
import Button from "react-bootstrap/Button";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

import ComponentLibrariesList from "../components/ComponentLibrariesList";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <h1>React Bootstrap Example</h1>
          <Row>
            <Col>
              <h3>A list of libraries to look at:</h3>
              <ComponentLibrariesList />
            </Col>
            <Col>
              <Button variant="info">Example</Button>
            </Col>
          </Row>
        </Container>
      </main>
    </div>
  );
}
